services:
    website:
        image: nginx:alpine
        restart: unless-stopped
        command: >
            /bin/sh -c "apk add --no-cache git &&
            rm -rf /usr/share/nginx/html/* &&
            git clone --depth 1 https://github.com/Enigmatiic/under-construction-template.git /tmp/site &&
            cp -r /tmp/site/. /usr/share/nginx/html/ &&
            nginx -g 'daemon off;'"
        volumes:
            - talmyma:/usr/share/nginx/html/
        labels:
            - traefik.enable=true
            - traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.ca`)
            - traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure
            - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt
            - traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80

